export const apiFake = [
  {
    id: '2312312312',
    name: 'Expresso Tradicional',
    tags: ['TRADICIONAL'],
    imageUrl: './src/assets/coffees/expresso_tradicional.png',
    description: 'O tradicional café feito com água quente e grãos moídos',
    price: 990,
    inventory: 10,
  },
  {
    id: '231232434545',
    name: 'Expresso Americano',
    tags: ['TRADICIONAL'],
    imageUrl: './src/assets/coffees/expresso_americano.png',
    description: 'Expresso diluído, menos intenso que o tradicional',
    price: 990,
    inventory: 10,
  },
  {
    id: '212111144',
    name: 'Expresso Cremoso',
    tags: ['TRADICIONAL'],
    imageUrl: './src/assets/coffees/expresso_cremoso.png',
    description: 'Café expresso tradicional com espuma cremosa',
    price: 990,
    inventory: 10,
  },
  {
    id: '222222222222333',
    name: 'Expresso Gelado',
    tags: ['TRADICIONAL', 'GELADO'],
    imageUrl: './src/assets/coffees/expresso_gelado.png',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    price: 990,
    inventory: 10,
  },
  {
    id: '434333334444',
    name: 'Café com Leite',
    tags: ['TRADICIONAL', 'COM LEITE'],
    imageUrl: './src/assets/coffees/cafe_com_leite.png',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    price: 990,
    inventory: 10,
  },
  {
    id: '546767676767',
    name: 'Latte',
    tags: ['TRADICIONAL', 'COM LEITE'],
    imageUrl: './src/assets/coffees/latte.png',
    description: 'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    price: 990,
    inventory: 10,
  },
  {
    id: '98988654444',
    name: 'Capuccino',
    tags: ['TRADICIONAL', 'COM LEITE'],
    imageUrl: './src/assets/coffees/capuccino.png',
    description: 'Bebida com canela feita de doses iguais de café, leite e espuma',
    price: 990,
    inventory: 10,
  },
  {
    id: '756574683333',
    name: 'Macchiato',
    tags: ['TRADICIONAL', 'COM LEITE'],
    imageUrl: './src/assets/coffees/macchiato.png',
    description: 'Café expresso misturado com um pouco de leite quente e espuma',
    price: 990,
    inventory: 10,
  },
  {
    id: '1233455675674',
    name: 'Mocaccino',
    tags: ['TRADICIONAL', 'COM LEITE'],
    imageUrl: './src/assets/coffees/mocaccino.png',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    price: 990,
    inventory: 10,
  },
  {
    id: '8908909000',
    name: 'Chocolate Quente',
    tags: ['ESPECIAL', 'COM LEITE'],
    imageUrl: './src/assets/coffees/chocolate_quente.png',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    price: 990,
    inventory: 10,
  },
  {
    id: '7475754477745',
    name: 'Cubano',
    tags: ['ESPECIAL', 'ALCOÓLICO', 'GELADO'],
    imageUrl: './src/assets/coffees/cubano.png',
    description: 'Drink gelado de café expresso com rum, creme de leite e hortelã',
    price: 990,
    inventory: 10,
  },
  {
    id: '555555555553',
    name: 'Havaiano',
    tags: ['ESPECIAL'],
    imageUrl: './src/assets/coffees/havaiano.png',
    description: 'Bebida adocicada preparada com café e leite de coco',
    price: 990,
    inventory: 10,
  },
  {
    id: '7666666444444444',
    name: 'Árabe',
    tags: ['ESPECIAL'],
    imageUrl: './src/assets/coffees/arabe.png',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    price: 990,
    inventory: 10,
  },
  {
    id: '111111111132323232',
    name: 'Irlandês',
    tags: ['ESPECIAL', 'ALCOÓLICO'],
    imageUrl: './src/assets/coffees/irlandes.png',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    price: 990,
    inventory: 10,
  },
]